version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: nouchka/sqlite3
    volumes:
      - sqlite_data:/data

volumes:
  sqlite_data: